use std::collections::HashSet;

pub fn get_all_date_time_func() -> HashSet<String> {
    HashSet::from([
        "@@DATEFIRST".to_string(),
        "CURRENT_DATE".to_string(),
        "CURRENT_TIMESTAMP".to_string(),
        "CURRENT_TIMEZONE".to_string(),
        "CURRENT_TIMEZONE_ID".to_string(),
        "DATE_BUCKET".to_string(),
        "DATEADD".to_string(),
        "DATEDIFF".to_string(),
        "DATEDIFF_BIG".to_string(),
        "DATEFROMPARTS".to_string(),
        "DATENAME".to_string(),
        "DATEPART".to_string(),
        "DATETIME2FROMPARTS".to_string(),
        "DATETIMEFROMPARTS".to_string(),
        "DATETIMEOFFSETFROMPARTS".to_string(),
        "DATETRUNC".to_string(),
        "DAY".to_string(),
        "EOMONTH".to_string(),
        "GETDATE".to_string(),
        "GETUTCDATE".to_string(),
        "ISDATE".to_string(),
        "MONTH".to_string(),
        "SMALLDATETIMEFROMPARTS".to_string(),
        "SWITCHOFFSET".to_string(),
        "SYSDATETIME".to_string(),
        "SYSDATETIMEOFFSET".to_string(),
        "SYSUTCDATETIME".to_string(),
        "TIMEFROMPARTS".to_string(),
        "TODATETIMEOFFSET".to_string(),
        "YEAR".to_string(),
    ])
}

pub fn get_sql_server_date_time_func() -> HashSet<String> {
    HashSet::from([
        // "@@DATEFIRST".to_string(),
        // "CURRENT_TIMEZONE".to_string(),
        // "CURRENT_TIMEZONE_ID".to_string(),
        // "DATE_BUCKET".to_string(),
        // "DATEADD".to_string(),
        // "DATEDIFF".to_string(),
        // "DATEDIFF_BIG".to_string(),
        // "DATEFROMPARTS".to_string(),
        // "DATENAME".to_string(),
        // "DATEPART".to_string(),
        // "DATETIME2FROMPARTS".to_string(),
        // "DATETIMEFROMPARTS".to_string(),
        // "DATETIMEOFFSETFROMPARTS".to_string(),
        // "DATETRUNC".to_string(),
        // "DAY".to_string(),
        // "EOMONTH".to_string(),
        // "GETDATE".to_string(),
        // "GETUTCDATE".to_string(),
        // "ISDATE".to_string(),
        // "MONTH".to_string(),
        // "SMALLDATETIMEFROMPARTS".to_string(),
        // "SWITCHOFFSET".to_string(),
        // "SYSDATETIME".to_string(),
        // "SYSDATETIMEOFFSET".to_string(),
        // "SYSUTCDATETIME".to_string(),
        // "TIMEFROMPARTS".to_string(),
        // "TODATETIMEOFFSET".to_string(),
        "YEAR".to_string(),
    ])
}
