use std::collections::HashSet;

// pub fn get_all_keywords() -> HashSet<String> {
//     HashSet::from([
//         "ADD".to_string(),
//         "EXTERNAL".to_string(),
//         "PROCEDURE".to_string(),
//         "ALL".to_string(),
//         "FETCH".to_string(),
//         "PUBLIC".to_string(),
//         "ALTER".to_string(),
//         "FILE".to_string(),
//         "RAISERROR".to_string(),
//         "AND".to_string(),
//         "FILLFACTOR".to_string(),
//         "READ".to_string(),
//         "ANY".to_string(),
//         "FOR".to_string(),
//         "READTEXT".to_string(),
//         "AS".to_string(),
//         "FOREIGN".to_string(),
//         "RECONFIGURE".to_string(),
//         "ASC".to_string(),
//         "FREETEXT".to_string(),
//         "REFERENCES".to_string(),
//         "AUTHORIZATION".to_string(),
//         "FREETEXTTABLE".to_string(),
//         "REPLICATION".to_string(),
//         "BACKUP".to_string(),
//         "FROM".to_string(),
//         "RESTORE".to_string(),
//         "BEGIN".to_string(),
//         "FULL".to_string(),
//         "RESTRICT".to_string(),
//         "BETWEEN".to_string(),
//         "FUNCTION".to_string(),
//         "RETURN".to_string(),
//         "BREAK".to_string(),
//         "GOTO".to_string(),
//         "REVERT".to_string(),
//         "BROWSE".to_string(),
//         "GRANT".to_string(),
//         "REVOKE".to_string(),
//         "BULK".to_string(),
//         "GROUP".to_string(),
//         "RIGHT".to_string(),
//         "BY".to_string(),
//         "HAVING".to_string(),
//         "ROLLBACK".to_string(),
//         "CASCADE".to_string(),
//         "HOLDLOCK".to_string(),
//         "ROWCOUNT".to_string(),
//         "CASE".to_string(),
//         "IDENTITY".to_string(),
//         "ROWGUIDCOL".to_string(),
//         "CHECK".to_string(),
//         "IDENTITY_INSERT".to_string(),
//         "RULE".to_string(),
//         "CHECKPOINT".to_string(),
//         "IDENTITYCOL".to_string(),
//         "SAVE".to_string(),
//         "CLOSE".to_string(),
//         "IF".to_string(),
//         "SCHEMA".to_string(),
//         "CLUSTERED".to_string(),
//         "IN".to_string(),
//         "SECURITYAUDIT".to_string(),
//         "COALESCE".to_string(),
//         "INDEX".to_string(),
//         "SELECT".to_string(),
//         "COLLATE".to_string(),
//         "INNER".to_string(),
//         "SEMANTICKEYPHRASETABLE".to_string(),
//         "COLUMN".to_string(),
//         "INSERT".to_string(),
//         "SEMANTICSIMILARITYDETAILSTABLE".to_string(),
//         "COMMIT".to_string(),
//         "INTERSECT".to_string(),
//         "SEMANTICSIMILARITYTABLE".to_string(),
//         "COMPUTE".to_string(),
//         "INTO".to_string(),
//         "SESSION_USER".to_string(),
//         "CONSTRAINT".to_string(),
//         "IS".to_string(),
//         "SET".to_string(),
//         "CONTAINS".to_string(),
//         "JOIN".to_string(),
//         "SETUSER".to_string(),
//         "CONTAINSTABLE".to_string(),
//         "KEY".to_string(),
//         "SHUTDOWN".to_string(),
//         "CONTINUE".to_string(),
//         "KILL".to_string(),
//         "SOME".to_string(),
//         "CONVERT".to_string(),
//         "LEFT".to_string(),
//         "STATISTICS".to_string(),
//         "CREATE".to_string(),
//         "LIKE".to_string(),
//         "SYSTEM_USER".to_string(),
//         "CROSS".to_string(),
//         "LINENO".to_string(),
//         "TABLE".to_string(),
//         "CURRENT".to_string(),
//         "LOAD".to_string(),
//         "TABLESAMPLE".to_string(),
//         "CURRENT_DATE".to_string(),
//         "MERGE".to_string(),
//         "TEXTSIZE".to_string(),
//         "CURRENT_TIME".to_string(),
//         "NATIONAL".to_string(),
//         "THEN".to_string(),
//         "CURRENT_TIMESTAMP".to_string(),
//         "NOCHECK".to_string(),
//         "TO".to_string(),
//         "CURRENT_USER".to_string(),
//         "NONCLUSTERED".to_string(),
//         "TOP".to_string(),
//         "CURSOR".to_string(),
//         "NOT".to_string(),
//         "TRAN".to_string(),
//         "DATABASE".to_string(),
//         "NULL".to_string(),
//         "TRANSACTION".to_string(),
//         "DBCC".to_string(),
//         "NULLIF".to_string(),
//         "TRIGGER".to_string(),
//         "DEALLOCATE".to_string(),
//         "OF".to_string(),
//         "TRUNCATE".to_string(),
//         "DECLARE".to_string(),
//         "OFF".to_string(),
//         "TRY_CONVERT".to_string(),
//         "DEFAULT".to_string(),
//         "OFFSETS".to_string(),
//         "TSEQUAL".to_string(),
//         "DELETE".to_string(),
//         "ON".to_string(),
//         "UNION".to_string(),
//         "DENY".to_string(),
//         "OPEN".to_string(),
//         "UNIQUE".to_string(),
//         "DESC".to_string(),
//         "OPENDATASOURCE".to_string(),
//         "UNPIVOT".to_string(),
//         "DISK".to_string(),
//         "OPENQUERY".to_string(),
//         "UPDATE".to_string(),
//         "DISTINCT".to_string(),
//         "OPENROWSET".to_string(),
//         "UPDATETEXT".to_string(),
//         "DISTRIBUTED".to_string(),
//         "OPENXML".to_string(),
//         "USE".to_string(),
//         "DOUBLE".to_string(),
//         "OPTION".to_string(),
//         "USER".to_string(),
//         "DROP".to_string(),
//         "OR".to_string(),
//         "VALUES".to_string(),
//         "DUMP".to_string(),
//         "ORDER".to_string(),
//         "VARYING".to_string(),
//         "ELSE".to_string(),
//         "OUTER".to_string(),
//         "VIEW".to_string(),
//         "END".to_string(),
//         "OVER".to_string(),
//         "WAITFOR".to_string(),
//         "ERRLVL".to_string(),
//         "PERCENT".to_string(),
//         "WHEN".to_string(),
//         "ESCAPE".to_string(),
//         "PIVOT".to_string(),
//         "WHERE".to_string(),
//         "EXCEPT".to_string(),
//         "PLAN".to_string(),
//         "WHILE".to_string(),
//         "EXEC".to_string(),
//         "PRECISION".to_string(),
//         "WITH".to_string(),
//         "EXECUTE".to_string(),
//         "PRIMARY".to_string(),
//         "WITHIN GROUP".to_string(),
//         "EXISTS".to_string(),
//         "PRINT".to_string(),
//         "WRITETEXT".to_string(),
//         "EXIT".to_string(),
//         "PROC".to_string(),
//     ])
// }

pub fn get_sql_server_keywords() -> HashSet<String> {
    HashSet::from([
        "BACKUP".to_string(),
        "BROWSE".to_string(),
        "BULK".to_string(),
        "CHECKPOINT".to_string(),
        "CLUSTERED".to_string(),
        "COMPUTE".to_string(),
        "CONTAINS".to_string(),
        "CONTAINSTABLE".to_string(),
        "DBCC".to_string(),
        "DENY".to_string(),
        "DISTRIBUTED".to_string(),
        "DUMPDUMP".to_string(),
        "ERRLVL".to_string(),
        "FILLFACTOR".to_string(),
        "FREETEXT".to_string(),
        "FREETEXTTABLE".to_string(),
        "HOLDLOCK".to_string(),
        "IDENTITY".to_string(),
        "IDENTITY_INSERT".to_string(),
        "IDENTITYCOL".to_string(),
        "KILL".to_string(),
        "LINENO".to_string(),
        //"LOAD".to_string(), // *
        "NOCHECK".to_string(),
        "NONCLUSTERED".to_string(),
        //"OFF".to_string(), // *
        "OPENDATASOURCE".to_string(),
        "OPENQUERY".to_string(),
        "OPENROWSET".to_string(),
        "OPENXML".to_string(),
        //"OPTION".to_string(), // *
        //"PERCENT".to_string(), // *
        "PIVOT".to_string(),
        //"PRINT".to_string(), // *
        //"PROC".to_string(), // *
        "RAISERROR".to_string(),
        "READTEXT".to_string(),
        "RECONFIGURE".to_string(),
        "REPLICATION".to_string(),
        "REVERT".to_string(),
        "ROWCOUNT".to_string(), // ***
        "ROWGUIDCOL".to_string(),
        //"RULE".to_string(), // *
        "SECURITYAUDIT".to_string(),
        "SEMANTICKEYPHRASETABLE".to_string(),
        "SEMANTICSIMILARITYDETAILSTABLE".to_string(),
        "SEMANTICSIMILARITYTABLE".to_string(),
        "SETUSER".to_string(),
        "SHUTDOWN".to_string(),
        //"STATISTICS".to_string(), // *
        "TABLESAMPLE".to_string(),
        "TEXTSIZE".to_string(),
        //"TOP".to_string(), // *
        "TSEQUAL".to_string(),
        "TRY_CONVERT".to_string(),
        "UNPIVOT".to_string(),
        "UPDATETEXT".to_string(),
        "WAITFOR".to_string(),
        "WRITETEXT".to_string(),
        "DUMP".to_string(),
    ])
}
