// Metadata
// @@PROCID
// APP_NAME
// APPLOCK_MODE
// APPLOCK_TEST
// ASSEMBLYPROPERTY
// COL_LENGTH
// COL_NAME
// COLUMNPROPERTY
// DATABASEPROPERTYEX
// DB_ID
// DB_NAME
// FILE_ID
// FILE_IDEX
// FILE_NAME
// FILEGROUP_ID
// FILEGROUP_NAME
// FILEGROUPPROPERTY
// FILEPROPERTY
// FILEPROPERTYEX
// FULLTEXTCATALOGPROPERTY
// FULLTEXTSERVICEPROPERTY
// INDEX_COL
// INDEXKEY_PROPERTY
// INDEXPROPERTY
// NEXT VALUE FOR
// OBJECT_DEFINITION
// OBJECT_ID
// OBJECT_NAME
// OBJECT_SCHEMA_NAME
// OBJECTPROPERTY
// OBJECTPROPERTYEX
// ORIGINAL_DB_NAME
// PARSENAME
// SCHEMA_ID
// SCHEMA_NAME
// SCOPE_IDENTITY
// SERVERPROPERTY
// STATS_DATE
// TYPE_ID
// TYPE_NAME
// TYPEPROPERTY

use std::collections::HashSet;

pub fn get_all_metadata_func() -> HashSet<String> {
    HashSet::from([
        //"COLLATIONPROPERTY".to_string(),

    ])
}

pub fn get_sql_server_metadata_func() -> HashSet<String> {
    HashSet::from([
        //"COLLATIONPROPERTY".to_string(),

    ])
}
