use std::collections::HashSet;

// pub fn get_all_metadata_func() -> HashSet<String> {
//     HashSet::from([
//         "@@PROCID".to_string(),
//         "APP_NAME".to_string(),
//         "APPLOCK_MODE".to_string(),
//         "APPLOCK_TEST".to_string(),
//         "ASSEMBLYPROPERTY".to_string(),
//         "COL_LENGTH".to_string(),
//         "COL_NAME".to_string(),
//         "COLUMNPROPERTY".to_string(),
//         "DATABASEPROPERTYEX".to_string(),
//         "DB_ID".to_string(),
//         "DB_NAME".to_string(),
//         "FILE_ID".to_string(),
//         "FILE_IDEX".to_string(),
//         "FILE_NAME".to_string(),
//         "FILEGROUP_ID".to_string(),
//         "FILEGROUP_NAME".to_string(),
//         "FILEGROUPPROPERTY".to_string(),
//         "FILEPROPERTY".to_string(),
//         "FILEPROPERTYEX".to_string(),
//         "FULLTEXTCATALOGPROPERTY".to_string(),
//         "FULLTEXTSERVICEPROPERTY".to_string(),
//         "INDEX_COL".to_string(),
//         "INDEXKEY_PROPERTY".to_string(),
//         "INDEXPROPERTY".to_string(),
//         "NEXT VALUE FOR".to_string(),
//         "OBJECT_DEFINITION".to_string(),
//         "OBJECT_ID".to_string(),
//         "OBJECT_NAME".to_string(),
//         "OBJECT_SCHEMA_NAME".to_string(),
//         "OBJECTPROPERTY".to_string(),
//         "OBJECTPROPERTYEX".to_string(),
//         "ORIGINAL_DB_NAME".to_string(),
//         "PARSENAME".to_string(),
//         "SCHEMA_ID".to_string(),
//         "SCHEMA_NAME".to_string(),
//         "SCOPE_IDENTITY".to_string(),
//         "SERVERPROPERTY".to_string(),
//         "STATS_DATE".to_string(),
//         "TYPE_ID".to_string(),
//         "TYPE_NAME".to_string(),
//         "TYPEPROPERTY".to_string(),
//     ])
// }

pub fn get_sql_server_metadata_func() -> HashSet<String> {
    HashSet::from([
        "@@PROCID".to_string(),
        "APP_NAME".to_string(),
        "APPLOCK_MODE".to_string(),
        "APPLOCK_TEST".to_string(),
        "ASSEMBLYPROPERTY".to_string(),
        "COL_LENGTH".to_string(),
        "COL_NAME".to_string(),
        "COLUMNPROPERTY".to_string(),
        "DATABASEPROPERTYEX".to_string(),
        "DB_ID".to_string(),
        "DB_NAME".to_string(),
        "FILE_ID".to_string(),
        "FILE_IDEX".to_string(),
        "FILE_NAME".to_string(),
        "FILEGROUP_ID".to_string(),
        "FILEGROUP_NAME".to_string(),
        "FILEGROUPPROPERTY".to_string(),
        "FILEPROPERTY".to_string(),
        "FILEPROPERTYEX".to_string(),
        "FULLTEXTCATALOGPROPERTY".to_string(),
        "FULLTEXTSERVICEPROPERTY".to_string(),
        "INDEX_COL".to_string(),
        "INDEXKEY_PROPERTY".to_string(),
        "INDEXPROPERTY".to_string(),
        "NEXT VALUE FOR".to_string(),
        "OBJECT_DEFINITION".to_string(),
        "OBJECT_ID".to_string(),
        "OBJECT_NAME".to_string(),
        "OBJECT_SCHEMA_NAME".to_string(),
        "OBJECTPROPERTY".to_string(),
        "OBJECTPROPERTYEX".to_string(),
        "ORIGINAL_DB_NAME".to_string(),
        "PARSENAME".to_string(),
        "SCHEMA_ID".to_string(),
        "SCHEMA_NAME".to_string(),
        "SCOPE_IDENTITY".to_string(),
        "SERVERPROPERTY".to_string(),
        "STATS_DATE".to_string(),
        "TYPE_ID".to_string(),
        "TYPE_NAME".to_string(),
        "TYPEPROPERTY".to_string(),
    ])
}
