use std::collections::HashSet;

// pub fn get_all_system_func() -> HashSet<String> {
//     HashSet::from([
//         "$PARTITION".to_string(),
//         "@@ERROR".to_string(),
//         "@@IDENTITY".to_string(),
//         "@@PACK_RECEIVED".to_string(),
//         "@@ROWCOUNT".to_string(),
//         "@@TRANCOUNT".to_string(),
//         "BINARY_CHECKSUM".to_string(),
//         "CHECKSUM".to_string(),
//         "COMPRESS".to_string(),
//         "CONNECTIONPROPERTY".to_string(),
//         "CONTEXT_INFO".to_string(),
//         "CURRENT_REQUEST_ID".to_string(),
//         "CURRENT_TRANSACTION_ID".to_string(),
//         "DECOMPRESS".to_string(),
//         "ERROR_LINE".to_string(),
//         "ERROR_MESSAGE".to_string(),
//         "ERROR_NUMBER".to_string(),
//         "ERROR_PROCEDURE".to_string(),
//         "ERROR_SEVERITY".to_string(),
//         "ERROR_STATE".to_string(),
//         "FORMATMESSAGE".to_string(),
//         "GET_FILESTREAM_TRANSACTION_CONTEXT".to_string(),
//         "GETANSINULL".to_string(),
//         "HOST_ID".to_string(),
//         "HOST_NAME".to_string(),
//         "ISNULL".to_string(),
//         "ISNUMERIC".to_string(),
//         "MIN_ACTIVE_ROWVERSION".to_string(),
//         "NEWID".to_string(),
//         "NEWSEQUENTIALID".to_string(),
//         "ROWCOUNT_BIG".to_string(),
//         "SESSION_CONTEXT".to_string(),
//         "XACT_STATE".to_string(),
//     ])
// }

pub fn get_sql_server_system_func() -> HashSet<String> {
    HashSet::from([
        "$PARTITION".to_string(),
        "@@ERROR".to_string(),
        "@@IDENTITY".to_string(),
        "@@PACK_RECEIVED".to_string(),
        "@@ROWCOUNT".to_string(),
        "@@TRANCOUNT".to_string(),
        "BINARY_CHECKSUM".to_string(),
        "CHECKSUM".to_string(),
        "COMPRESS".to_string(),
        "CONNECTIONPROPERTY".to_string(),
        "CONTEXT_INFO".to_string(),
        "CURRENT_REQUEST_ID".to_string(),
        "CURRENT_TRANSACTION_ID".to_string(),
        "DECOMPRESS".to_string(),
        "ERROR_LINE".to_string(),
        "ERROR_MESSAGE".to_string(),
        "ERROR_NUMBER".to_string(),
        "ERROR_PROCEDURE".to_string(),
        "ERROR_SEVERITY".to_string(),
        "ERROR_STATE".to_string(),
        "FORMATMESSAGE".to_string(),
        "GET_FILESTREAM_TRANSACTION_CONTEXT".to_string(),
        "GETANSINULL".to_string(),
        "HOST_ID".to_string(),
        "HOST_NAME".to_string(),
        "ISNULL".to_string(),
        "ISNUMERIC".to_string(),
        "MIN_ACTIVE_ROWVERSION".to_string(),
        "NEWID".to_string(),
        "NEWSEQUENTIALID".to_string(),
        "ROWCOUNT_BIG".to_string(),
        "SESSION_CONTEXT".to_string(),
        "XACT_STATE".to_string(),
    ])
}
